name: flutter_application_1
description: Proyecto Pokémon estilo Pokédex con entrenadores
publish_to: 'none' # no publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquetes útiles
  cupertino_icons: ^1.0.6
  youtube_player_flutter: ^9.1.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/entrenadores/
    - assets/pokemons/
